import React, { useState } from 'react';
import { Hotel } from './types';
import { Header } from './components/Header';
import HomePage from './components/HomePage';
import AboutPage from './components/AboutPage';
import ContactPage from './components/ContactPage';
import CheckoutPage from './components/CheckoutPage';

type Page = 'home' | 'about' | 'contact' | 'checkout';

const App: React.FC = () => {
  const [currentPage, setCurrentPage] = useState<Page>('home');
  const [basket, setBasket] = useState<Hotel[]>([]);

  const handleNavigate = (page: Page) => {
    setCurrentPage(page);
    window.scrollTo(0, 0);
  };

  const handleAddToBasket = (hotel: Hotel) => {
    // Prevent adding the same hotel multiple times
    if (!basket.find(item => item.name === hotel.name)) {
      setBasket(prevBasket => [...prevBasket, hotel]);
    }
  };

  const handleRemoveFromBasket = (hotelName: string) => {
    setBasket(prevBasket => prevBasket.filter(item => item.name !== hotelName));
  };

  const renderPage = () => {
    switch (currentPage) {
      case 'home':
        return <HomePage onAddToBasket={handleAddToBasket} />;
      case 'about':
        return <AboutPage />;
      case 'contact':
        return <ContactPage />;
      case 'checkout':
        return <CheckoutPage basket={basket} onRemoveFromBasket={handleRemoveFromBasket} onNavigateHome={() => handleNavigate('home')} />;
      default:
        return <HomePage onAddToBasket={handleAddToBasket} />;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 flex flex-col">
      <Header onNavigate={handleNavigate} basketCount={basket.length} />
      
      <main className="flex-grow">
        {renderPage()}
      </main>

      <footer className="bg-white mt-12">
        <div className="container mx-auto px-8 py-6 text-center text-gray-500 text-sm">
          <p>&copy; {new Date().getFullYear()} StayFinder. All rights reserved.</p>
          <p className="mt-1">Hotel data is generated by AI for demonstration purposes.</p>
        </div>
      </footer>
    </div>
  );
};

export default App;
