import React from 'react';
import { LogoIcon } from './icons';

const AboutPage: React.FC = () => {
  return (
    <div className="bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="max-w-3xl mx-auto text-center">
            <LogoIcon className="mx-auto h-20 w-20 text-brand-primary" />
          <h1 className="text-4xl font-bold text-gray-900 mt-4">About StayFinder</h1>
          <p className="mt-4 text-lg text-gray-600">
            Welcome to the future of travel planning.
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto mt-12 text-gray-700 space-y-6 text-left leading-relaxed">
            <p>
                StayFinder is a revolutionary concept in hotel booking, born from a passion for both technology and travel. We believe that finding the perfect place to stay should be as exciting as the journey itself. That's why we've harnessed the power of Google's Gemini AI to create a unique and dynamic discovery experience.
            </p>
            <p>
                Unlike traditional booking sites that rely on static databases, StayFinder generates hotel listings in real-time based on your search. Each hotel, with its creative name, compelling description, and curated amenities, is a product of AI imagination, designed to spark your wanderlust. The images are sourced to match the vibe of your chosen destination, making every search a new adventure.
            </p>
             <h2 className="text-2xl font-semibold text-gray-800 pt-4">Our Mission</h2>
            <p>
                Our mission is to make travel planning effortless, inspiring, and fun. We aim to break the mold of tedious, filter-heavy search processes by offering a more intuitive and engaging way to explore potential stays. By leveraging cutting-edge AI, we provide you with endless possibilities, ensuring you can always find a "place" that perfectly fits your dream vacation.
            </p>
             <h2 className="text-2xl font-semibold text-gray-800 pt-4">The Technology</h2>
             <p>
                This application is a demonstration of the creative and practical power of large language models. The entire backend is powered by the Gemini API, which handles the complex task of generating structured, realistic, and appealing hotel data on the fly. The frontend is built with React and Tailwind CSS, creating a responsive and beautiful user interface.
            </p>
            <p className="pt-8 text-center text-gray-500 italic">
                Please note: All hotel listings are fictional and generated by AI for demonstration purposes only.
            </p>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
