import React, { useState, useCallback } from 'react';
import { Hotel, SearchFilters } from '../types';
import { fetchHotels } from '../services/geminiService';
import { FilterBar } from './SearchBar';
import { HotelCard } from './HotelCard';
import { HotelDetailModal } from './HotelDetailModal';
import { SkeletonCard } from './SkeletonCard';
import { SearchIcon } from './icons';

interface HomePageProps {
  onAddToBasket: (hotel: Hotel) => void;
}

const HomePage: React.FC<HomePageProps> = ({ onAddToBasket }) => {
  const [hotels, setHotels] = useState<Hotel[]>([]);
  const [bookedHotelNames, setBookedHotelNames] = useState<Set<string>>(new Set());
  const [selectedHotel, setSelectedHotel] = useState<Hotel | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [hasSearched, setHasSearched] = useState<boolean>(false);

  const handleSearch = useCallback(async (filters: SearchFilters) => {
    if (!filters.city) {
      setError("Please enter a city to search.");
      return;
    }
    
    setIsLoading(true);
    setHasSearched(true);
    setError(null);
    setHotels([]);

    try {
      const fetchParams = {
        city: filters.city,
        country: filters.country,
        priceMin: filters.priceMin ? parseInt(filters.priceMin, 10) : undefined,
        priceMax: filters.priceMax ? parseInt(filters.priceMax, 10) : undefined,
      };
      if (fetchParams.priceMin && fetchParams.priceMax && fetchParams.priceMin > fetchParams.priceMax) {
        setError("Minimum price cannot be greater than maximum price.");
        setIsLoading(false);
        return;
      }

      const results = await fetchHotels(fetchParams);
      setHotels(results);
    } catch (err) {
      setError("Failed to fetch hotel data. The AI might be busy, please try again.");
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleSelectHotel = (hotel: Hotel) => {
    setSelectedHotel(hotel);
  };

  const handleCloseModal = () => {
    setSelectedHotel(null);
  };

  const handleBookHotel = (hotel: Hotel) => {
    onAddToBasket(hotel);
    setBookedHotelNames(prev => new Set(prev).add(hotel.name));
  };
  
  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {Array.from({ length: 8 }).map((_, index) => (
            <SkeletonCard key={index} />
          ))}
        </div>
      );
    }

    if (error) {
        return (
            <div className="text-center py-20 px-4">
                <p className="text-red-500 bg-red-100 p-4 rounded-lg">{error}</p>
            </div>
        );
    }

    if (!hasSearched) {
        return (
            <div className="text-center py-20 px-4">
                <SearchIcon className="mx-auto h-24 w-24 text-gray-300" />
                <h2 className="mt-4 text-2xl font-semibold text-gray-700">Find your next stay</h2>
                <p className="mt-2 text-gray-500">Use the filters above to discover amazing hotels generated by AI.</p>
            </div>
        );
    }

    if (hotels.length > 0) {
      return (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-x-6 gap-y-10">
          {hotels.map((hotel, index) => (
            <HotelCard key={`${hotel.name}-${index}`} hotel={hotel} onSelect={handleSelectHotel} />
          ))}
        </div>
      );
    }

    if (hasSearched && hotels.length === 0) {
        return (
            <div className="text-center py-20 px-4">
                <h2 className="text-2xl font-semibold text-gray-700">No results found</h2>
                <p className="mt-2 text-gray-500">The AI couldn't find any hotels for that destination. Try another search.</p>
            </div>
        );
    }

    return null;
  };

  return (
    <>
      <div className="container mx-auto p-4 sm:p-6 lg:p-8">
        <div className="bg-white p-4 sm:p-6 rounded-xl shadow-sm mb-8">
            <FilterBar onSearch={handleSearch} isLoading={isLoading} />
        </div>
        {renderContent()}
      </div>

      {selectedHotel && (
        <HotelDetailModal 
          hotel={selectedHotel} 
          onClose={handleCloseModal}
          onBook={handleBookHotel}
          isBooked={bookedHotelNames.has(selectedHotel.name)}
        />
      )}
    </>
  );
};

export default HomePage;
